# Generated by Django 5.2.4 on 2025-07-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('seoul', '서울'), ('cheonan', '천안'), ('employment', '채용')], default='상명', max_length=20),
            preserve_default=False,
        ),
    ]
