# Generated by Django 5.2.4 on 2025-07-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PwdResetEmail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailauthcode',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emailauthcode',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
