# Generated by Django 5.2.4 on 2025-07-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('entry_type', models.CharField(max_length=20)),
                ('lib_req', models.IntegerField()),
                ('lib_sel', models.IntegerField()),
                ('lib_total', models.IntegerField()),
                ('major_core', models.IntegerField()),
                ('major_sel', models.IntegerField()),
                ('major_total', models.IntegerField()),
                ('multi_major_total', models.IntegerField()),
                ('first_major', models.IntegerField()),
                ('sub_major', models.IntegerField()),
                ('remain_credit', models.IntegerField()),
                ('grad_avg', models.FloatField()),
                ('gpa_grad', models.FloatField()),
                ('gpa_early', models.FloatField()),
            ],
        ),
    ]
