# Generated by Django 5.2.4 on 2025-07-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduationrequirement',
            old_name='first_major',
            new_name='double_req',
        ),
        migrations.RenameField(
            model_name='graduationrequirement',
            old_name='multi_major_total',
            new_name='double_sel',
        ),
        migrations.RenameField(
            model_name='graduationrequirement',
            old_name='sub_major',
            new_name='sub_major1',
        ),
        migrations.AddField(
            model_name='graduationrequirement',
            name='double_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graduationrequirement',
            name='sub_major2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
