# Generated by Django 5.2.4 on 2025-07-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0002_rename_first_major_graduationrequirement_double_req_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduationrequirement',
            name='gpa_early',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graduationrequirement',
            name='sub_major1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
