# Generated by Django 5.2.4 on 2025-07-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0003_alter_graduationrequirement_gpa_early_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduationrequirement',
            name='major_core',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
