# Generated by Django 5.2.4 on 2025-07-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_notice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=models.CharField(blank=True, default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
