# Generated by Django 5.2.4 on 2025-07-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=10)),
                ('total_credit', models.IntegerField()),
                ('grade_point', models.FloatField()),
                ('grade_average', models.FloatField()),
                ('percentile', models.FloatField()),
                ('rank', models.CharField(max_length=20)),
            ],
        ),
    ]
