# Generated by Django 5.2.4 on 2025-07-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('credit', models.IntegerField()),
                ('semester', models.CharField(max_length=10)),
                ('day_time', models.CharField(max_length=50)),
                ('professor', models.CharField(max_length=50)),
            ],
        ),
    ]
