# Generated by Django 5.2.4 on 2025-07-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', '관리자'), ('professor', '교수'), ('student', '학생')], default='student', max_length=20),
        ),
    ]
